models/alert.py
import uuid
from models.item import Item
from common.database import Database


class Alert:

    def __init__(self, item_id, price_limit, _id = None):
        self.item_id = item_id
        self.item = Item.get_by_id(item_id)
        self.price_limit = price_limit
        self.collection = "alerts"
        self._id = uuid.uuid4().hex if _id is None else _id

    def json(self):
        return {
            "_id":self._id,
            "item_id": self.item_id,
            "price_limit":self.price_limit
        }
        

    def saveToDb(self):
        Database.insert(self.collection, self.json())

    def load_item_price(self):
        return self.item.load_price()

    def notify_if_price_reached(self):
        if self.load_item_price() < self.price_limit:
            print("Item {} has reached a price under {}".format(self.item, self.price_limit))

    @classmethod    
    def all(cls):
        alert_from_db = Database.find("alerts", {})
        return[ cls(**alert) for alert in alert_from_db]

models/item.py
import requests
from bs4 import BeautifulSoup
import re
import uuid
from common.database import Database


class Item:

    def __init__(self, url, tag_name, query, _id = None):
        self.url = url
        self.tag_name = tag_name
        self.query = query
        #
        self.collection = "items"
        self._id = uuid.uuid4().hex if _id is None else _id

    def __repr__(self):
        return "Item {} ".format(self.url)

    def load_price(self):
        res = requests.get(self.url)

        content = res.content

        soup = BeautifulSoup(content, 'html.parser')

        element = soup.find(self.tag_name, self.query).text.strip()


        pattern = re.compile(r"(\d?,?\d\d\d.\d\d)") #加上?代表說是不一定要有
        match = pattern.search(element)

        self.price = float(match.group(1).replace(",",""))

        return self.price

    def saveToDb(self):
        Database.insert(self.collection, self.json())


    def json(self):
        return {
            "_id" : self._id,
            "url" : self.url,
            "tag_name" : self.tag_name,
            "query" : self.query,
        }


    @classmethod
    def get_all(cls):
        items_from_db = Database.find('items', {})
        return [cls(**item) for item in items_from_db] 

    @classmethod
    def get_by_id(cls, id):
        item_json = Database.find_one("items", {"_id":id})
        return cls(**item_json)



"""
#########################################################
#add comment#
#########################################################

url = 'https://www.johnlewis.com/john-lewis-partners-frame-leather-office-chair-natural-oak/p4273087'

Tag_name = "p"
Query = {'class':'price price--large'}

res = requests.get(url)

content = res.content

soup = BeautifulSoup(content, 'html.parser')

element = soup.find(Tag_name, Query).text.strip()


pattern = re.compile(r"(\d?,?\d\d\d.\d\d)") #加上?代表說是不一定要有
match = pattern.search(element)

price = float(match.group(1).replace(",",""))

"""

app.py
from flask import Flask, render_template, request
from models.item import Item
from views.items import item_blueprint
from views.users import user_blueprint

app = Flask(__name__)

app.register_blueprint(item_blueprint, url_prefix='/items')
app.register_blueprint(user_blueprint, url_prefix='/users')



if __name__ == '__main__':
    app.Debug = True
    app.run(port = 8150)

views/items.py
from flask import Flask, render_template, request, Blueprint
from models.item import Item


item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/')
def index():
    items = Item.get_all()
    return render_template('items/index.html', items=items)


@item_blueprint.route('/new', methods =['GET', 'POST'])
def new_item():
    if request.method == 'POST':
        url = request.form['url']
        tag_name = request.form['tag_name']
        query = request.form['query']
        Item(url, tag_name, query).saveToDb()

    return render_template('items/newitem.html')

views/users.py
from flask import Flask, render_template, request, Blueprint, session, url_for, redirect
from models.user import User, UserErrors


item_blueprint = Blueprint('users', __name__)


@item_blueprint.route('/register', methods =['GET', 'POST'])
def new_item():
    if request.method == 'POST':
        email = request.form['email']
        passw = request.form['password']
        try:
            User.register_user(email, passw)
            session['email'] = email # save session
        except UserErrors.UserError as e:
            return e.mssage

    return render_template('users/register.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Price alerts</title>
</head>
<body>


<div class="content container">
    {% block content %}

    {% endblock %}
</div>

    
</body>
</html>

templates/items/index.html
{% extends "base.html" %}

{% block content %}

<header>
    <h1>Items</h1>
</header>
<section>
    <div class="list-group mb-3">
        <!-- using for loop -->
        {% for item in items %}
            <div class="list-group-item">
                <h4>Item</h4>
                <p>
                    <a href="{{item.url}}" class="">{{ item.url}}</a>
                </p>

            </div>

        {% endfor %}
    </div>

    <!-- 有點神妙 表示前往 items 這個藍圖的new_item方法-->
    <a class="btn btn-primary mb-3" href="{{ url_for('items.new_item') }}"> 
        create new item
    </a>


</section>

{% endblock %}

templates/items/newitem.html
{% extends "base.html" %}

{% block content %}


    <header> <h1>Create Item</h1></header>

    <section class="create-item-form" >

        <form method="post" action="/">
            <div class="form-group">
                <label for="url" >URL</label>
                <input type="text" class="form-control" id = "url" name="url" placeholder="https://....">
            </div>
            <div class="form-group">
                <label for="tag_name" >Tag_name</label>
                <input type="text" class="form-control" id = "tag_name" name="tag_name" placeholder="span">
                <small id="tagNameHelp">
                    XXXX
                </small>
            </div>
            <div class="form-group">
                <label for="query" >query</label>
                <input type="text" class="form-control" id = "query" name="query" placeholder="{...}">
            </div>

            <button type="submit" class="btn btn-primary"> Create</button>

        </form>

    </section>



{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}

    <header> <h1>Register</h1></header>

    <section class="create-item-form" >

        <form method="post">
            <div class="form-group">
                <label for="email" >URL</label>
                <input type="text" class="form-control" id = "email" name="email " placeholder="XXXX@test.com.tw">
            </div>
            <div class="form-group">
                <label for="password" >password</label>
                <input type="text" class="form-control" id = "password" name="password" placeholder="span">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>

        </form>

    </section>



{% endblock %}